### ISSUE TITLE
Doesn't load on IE

### ISSUE THREAD

**Issue by nbgraham** [creatdevsolutions/cs-react-signature-pad#3]
I forked the repo
`npm install`
`npm run start`

Navigating to http://localhost:3000 works on something like Edge, but shows a blank screen on IE (Version 11.615.17763.0)

Syntax error
app.js (907,1)

This is the `class App extends react`... declaration

This is probably happening because there are a lot of arrow functions in this compiled app.js file and IE does not support them
https://stackoverflow.com/questions/42080078/javascript-syntax-error-on-internet-explorer

**Comment by johannwagner** [comment]
Sorry, we do not monitor this issue. You may want to check out the main repository.
